import { Navbar } from "@/components/shared/navbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({children}: {children: React.ReactNode}) {
    return <div className="min-h-screen bg-background">
        <Navbar />
        {children}
    </div>
}